### ISSUE TITLE
 [Render It!] ModUtils:PatchOptionsGraphicsPanel -> Exception: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by originalfoo** [keallu/CSL-RenderIt#1]
Spotted in the wild:

[renderit-output_log-1.txt](https://github.com/keallu/CSL-RenderIt/files/4513087/renderit-output_log-1.txt)

Note that Harmony 2.0.0.9 is now becoming prevalent; it auto-patches earlier versions of Harmony to improve compatibility.

More info here: https://steamcommunity.com/sharedfiles/filedetails/?id=2040656402

**Comment by keallu** [comment]
Render It! will be upgraded to Harmony 2 soon.

**Comment by keallu** [comment]
Upgraded to Harmony 2 so think this issue are squashed.
