### ISSUE TITLE
Button is not always in front when moving around

### ISSUE THREAD

**Issue by MenschLennart** [keallu/CSL-RenderIt#3]
As the title suggests, the button slides under the UI when I move it. This occurred after I deleted the addon's XML after the button disappeared.

**Comment by keallu** [comment]
Can you tell me which UI it slides under? Is it the menu bar at the bottom? A screen shot will be excellent. I know what the problem can be but I have already set the z-order on the button so it should be fine. It should be "on top" on everything else - in principle that is :)

**Comment by MenschLennart** [comment]
Sorry, didn't see your responses here. I guess, you fixed it with the newest update. Thank you 💯

**Comment by keallu** [comment]
Yes, it should be fixed now.
