### ISSUE TITLE
Activating bloom creates heavy contrast 

### ISSUE THREAD

**Issue by MenschLennart** [keallu/CSL-RenderIt#4]
When I activate Bloom and increase the intensity from zero to more, the contrast increases increasingly and changes the image completely.

It should be said that I have the following addons active. However, all settings of the addons are on default. 
- Daylight Classic
- Relight
- Ultimate Eyecandy

**Comment by keallu** [comment]
You can use all these mods with Render It! but it can have side effects. In general Bloom is very sensitive.

Relight does more or less the same as Color Grading in Render It! but with LUT. Color Grading is a more advanced method than the Look-Up Texture (LUT) which is the default 'color grading' method in the game and in Relight. They can be used together though.

I intend to add "shadow control" and more into Render It! which will replace the need for Daylight Classic and Ultimate Eyecandy eventually. But it all takes time :)

**Comment by keallu** [comment]
Bloom had an issue with threshold which is now fixed. Bloom effect is still very sensitive but I'm using the dafault intervals from the post processing stack.
