### ISSUE TITLE
Building texture settings are also used for other types.

### ISSUE THREAD

**Issue by neinnew** [keallu/CSL-RenderIt#5]
It appears that `[ProfileManager.Instance.ActiveProfile.BuildingsAnisoLevel]` and `[ProfileManager.Instance.ActiveProfile.BuildingsMipMapBias]` were incorrectly copied to all other types when version 1.16

**Comment by keallu** [comment]
Could you please elaborate on this?

**Comment by neinnew** [comment]
[https://github.com/keallu/CSL-RenderIt/blob/8a52f65717fc64e8bd43aa444b8f63c3a949d96f/RenderIt/Helpers/TextureHelper.cs#L114-L115](https://github.com/keallu/CSL-RenderIt/blob/8a52f65717fc64e8bd43aa444b8f63c3a949d96f/RenderIt/Helpers/TextureHelper.cs#L114-L115)

This is in UpdateNetwork()

**Comment by keallu** [comment]
Yes, I've just found it myself when looking into it. Thank you for reporting. It will be fixed in the next version.
