### ISSUE TITLE
Doubts about the possibility of anisotropic filtering level above 9

### ISSUE THREAD

**Issue by neinnew** [keallu/CSL-RenderIt#6]
I was searching for how Unity's anisotropic filtering level relates to common multiples (x2, x4, x8...) and found this:
[https://forum.unity.com/threads/anisotropic-textures-settings-in-quality-settings.463683/#post-3013887/](https://forum.unity.com/threads/anisotropic-textures-settings-in-quality-settings.463683/#post-3013887/)

>Edit: Been a while since I looked at the Aniso Level settings, but it's a straight 0-16 value, so anything 2 or greater maps directly to the "max anisotropic" setting. It appears Unity's documentation [here](https://docs.unity3d.com/ScriptReference/Texture-anisoLevel.html) is either wrong, or just out of date.
bgolus, Mar 31, 2017

According to this, 16 is may actually a valid value. I tried to compare it in the theme texture with Modtools and I could see the difference myself.

**Comment by keallu** [comment]
Well, it shouldn't apply if you look at the documentation for Unity 5.6 (which is the version used by Cities : Skylines):

https://docs.unity3d.com/560/Documentation/ScriptReference/Texture-anisoLevel.html

**Comment by neinnew** [comment]
[https://forum.unity.com/threads/different-settings-for-anisotropic-filtering-are-confusing.268052/#post-3078664](https://forum.unity.com/threads/different-settings-for-anisotropic-filtering-are-confusing.268052/#post-3078664)

But it seems like an old problem.

**Comment by keallu** [comment]
Ok, please provide screen shots if you have experience any difference with the new version 1.17 - when editing values with ModTools.

**Comment by neinnew** [comment]
![](https://i.imgur.com/PdAy8bR.png)

**Comment by keallu** [comment]
Ok, I will look into it a some time.

**Comment by keallu** [comment]
I've added level 10 to 16 in the latest version now.
